<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name="human_upper">

    <xacro:spherical name="base_to_upper_trunk" parent="base_link" child="upper_trunk">
        <origin rpy="0 0 0" xyz="0 0 ${thickness+l_shank+l_thigh+l_lower_trunk}"/>
    </xacro:spherical>
    
    <link name="upper_trunk">
        <visual>
        <origin rpy="0 0 0" xyz="0 0 ${l_upper_trunk/2}"/>
        <geometry>
            <cylinder length="${l_upper_trunk}" radius="${r_upper_trunk}"/>
        </geometry>
        <material name="white"/>
        </visual>
        <collision>
        <origin rpy="0 0 0" xyz="0 0 ${l_upper_trunk/2}"/>
        <geometry>
            <cylinder length="${l_upper_trunk}" radius="${r_upper_trunk}"/>
        </geometry>
        </collision>
        <inertial>
        <origin rpy="0 0 0" xyz="0 0 ${l_upper_trunk/2}"/>
        <mass value="${m_upper_trunk}"/>
        <inertia
            ixx="${m_upper_trunk*(3*pow(r_upper_trunk,2)+pow(l_upper_trunk,2))/12}" ixy="0.0" ixz="0.0"
            iyy="${m_upper_trunk*(3*pow(r_upper_trunk,2)+pow(l_upper_trunk,2))/12}" iyz="0.0"
            izz="${m_upper_trunk*pow(r_upper_trunk,2)/2}"/>
        </inertial>
    </link>

    <xacro:spherical name="left_shoulder" parent="upper_trunk" child="left_upper_arm">
        <origin rpy="0 0 0" xyz="0 ${-r_upper_trunk} ${l_upper_trunk}"/>
    </xacro:spherical>
    
    <link name="left_upper_arm">
        <visual>
        <origin rpy="0 0 0" xyz="0 0 ${-l_upper_arm/2}"/>
        <geometry>
            <cylinder length="${l_upper_arm}" radius="${r_upper_arm}"/>
        </geometry>
        <material name="blue"/>
        </visual>
        <collision>
        <origin rpy="0 0 0" xyz="0 0 ${-l_upper_arm/2}"/>
        <geometry>
            <cylinder length="${l_upper_arm}" radius="${r_upper_arm}"/>
        </geometry>
        </collision>
        <inertial>
        <origin rpy="0 0 0" xyz="0 0 ${-l_upper_arm/2}"/>
        <mass value="${m_upper_arm}"/>
        <inertia
            ixx="${m_upper_arm*(3*pow(r_upper_arm,2)+pow(l_upper_arm,2))/12}" ixy="0.0" ixz="0.0"
            iyy="${m_upper_arm*(3*pow(r_upper_arm,2)+pow(l_upper_arm,2))/12}" iyz="0.0"
            izz="${m_upper_arm*pow(r_upper_arm,2)/2}"/>
        </inertial>
    </link>

    

</xacro:macro>

</robot>
