# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_tool.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.groupBox_robots = QtWidgets.QGroupBox(Form)
        self.groupBox_robots.setGeometry(QtCore.QRect(60, 210, 641, 121))
        self.groupBox_robots.setObjectName("groupBox_robots")
        self.radioButton_simulation = QtWidgets.QRadioButton(self.groupBox_robots)
        self.radioButton_simulation.setGeometry(QtCore.QRect(170, 40, 112, 23))
        self.radioButton_simulation.setObjectName("radioButton_simulation")
        self.radioButton_real_robot = QtWidgets.QRadioButton(self.groupBox_robots)
        self.radioButton_real_robot.setGeometry(QtCore.QRect(470, 40, 112, 23))
        self.radioButton_real_robot.setObjectName("radioButton_real_robot")
        self.label = QtWidgets.QLabel(self.groupBox_robots)
        self.label.setGeometry(QtCore.QRect(360, 70, 67, 17))
        self.label.setObjectName("label")
        self.comboBox_robot_name = QtWidgets.QComboBox(self.groupBox_robots)
        self.comboBox_robot_name.setGeometry(QtCore.QRect(140, 70, 181, 25))
        self.comboBox_robot_name.setObjectName("comboBox_robot_name")
        self.label_6 = QtWidgets.QLabel(self.groupBox_robots)
        self.label_6.setGeometry(QtCore.QRect(30, 70, 91, 20))
        self.label_6.setObjectName("label_6")
        self.lineEdit_robot_ip = QtWidgets.QLineEdit(self.groupBox_robots)
        self.lineEdit_robot_ip.setGeometry(QtCore.QRect(440, 70, 181, 25))
        self.lineEdit_robot_ip.setObjectName("lineEdit_robot_ip")
        self.groupBox_human = QtWidgets.QGroupBox(Form)
        self.groupBox_human.setGeometry(QtCore.QRect(60, 40, 301, 151))
        self.groupBox_human.setObjectName("groupBox_human")
        self.label_2 = QtWidgets.QLabel(self.groupBox_human)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 111, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_human)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 111, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_human)
        self.label_4.setGeometry(QtCore.QRect(10, 90, 111, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_human)
        self.label_5.setGeometry(QtCore.QRect(10, 120, 111, 17))
        self.label_5.setObjectName("label_5")
        self.l_upper_trunk = QtWidgets.QLineEdit(self.groupBox_human)
        self.l_upper_trunk.setGeometry(QtCore.QRect(160, 30, 113, 25))
        self.l_upper_trunk.setObjectName("l_upper_trunk")
        self.l_upper_arm = QtWidgets.QLineEdit(self.groupBox_human)
        self.l_upper_arm.setGeometry(QtCore.QRect(160, 60, 113, 25))
        self.l_upper_arm.setObjectName("l_upper_arm")
        self.l_forearm = QtWidgets.QLineEdit(self.groupBox_human)
        self.l_forearm.setGeometry(QtCore.QRect(160, 90, 113, 25))
        self.l_forearm.setObjectName("l_forearm")
        self.l_hand = QtWidgets.QLineEdit(self.groupBox_human)
        self.l_hand.setGeometry(QtCore.QRect(160, 120, 113, 25))
        self.l_hand.setObjectName("l_hand")
        self.groupBox_actions = QtWidgets.QGroupBox(Form)
        self.groupBox_actions.setGeometry(QtCore.QRect(60, 340, 641, 211))
        self.groupBox_actions.setObjectName("groupBox_actions")
        self.pushButton_calibrate_human = QtWidgets.QPushButton(self.groupBox_actions)
        self.pushButton_calibrate_human.setGeometry(QtCore.QRect(30, 50, 131, 25))
        self.pushButton_calibrate_human.setObjectName("pushButton_calibrate_human")
        self.pushButton_connect_robot = QtWidgets.QPushButton(self.groupBox_actions)
        self.pushButton_connect_robot.setGeometry(QtCore.QRect(30, 90, 131, 25))
        self.pushButton_connect_robot.setObjectName("pushButton_connect_robot")
        self.pushButton_teleoperate = QtWidgets.QPushButton(self.groupBox_actions)
        self.pushButton_teleoperate.setGeometry(QtCore.QRect(260, 50, 131, 31))
        self.pushButton_teleoperate.setObjectName("pushButton_teleoperate")
        self.pushButton_colift = QtWidgets.QPushButton(self.groupBox_actions)
        self.pushButton_colift.setGeometry(QtCore.QRect(450, 50, 131, 31))
        self.pushButton_colift.setObjectName("pushButton_colift")
        self.textEdit_status = QtWidgets.QTextEdit(self.groupBox_actions)
        self.textEdit_status.setGeometry(QtCore.QRect(220, 90, 401, 101))
        self.textEdit_status.setObjectName("textEdit_status")
        self.pushButton_spawn_models = QtWidgets.QPushButton(self.groupBox_actions)
        self.pushButton_spawn_models.setGeometry(QtCore.QRect(30, 130, 131, 25))
        self.pushButton_spawn_models.setObjectName("pushButton_spawn_models")
        self.pushButton_start_controllers = QtWidgets.QPushButton(self.groupBox_actions)
        self.pushButton_start_controllers.setGeometry(QtCore.QRect(30, 170, 131, 25))
        self.pushButton_start_controllers.setObjectName("pushButton_start_controllers")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_robots.setTitle(_translate("Form", "Robots"))
        self.radioButton_simulation.setText(_translate("Form", "Simulation"))
        self.radioButton_real_robot.setText(_translate("Form", "Real robot"))
        self.label.setText(_translate("Form", "Robot IP:"))
        self.label_6.setText(_translate("Form", "Robot Name:"))
        self.groupBox_human.setTitle(_translate("Form", "Human Measurements"))
        self.label_2.setText(_translate("Form", "Upper trunk:"))
        self.label_3.setText(_translate("Form", "Upper arm:"))
        self.label_4.setText(_translate("Form", "Forearm:"))
        self.label_5.setText(_translate("Form", "Hand:"))
        self.groupBox_actions.setTitle(_translate("Form", "Actions"))
        self.pushButton_calibrate_human.setText(_translate("Form", "Calibrate Human"))
        self.pushButton_connect_robot.setText(_translate("Form", "Connect to Robot"))
        self.pushButton_teleoperate.setText(_translate("Form", "Teleoperate"))
        self.pushButton_colift.setText(_translate("Form", "Colift"))
        self.pushButton_spawn_models.setText(_translate("Form", "Spawn Models"))
        self.pushButton_start_controllers.setText(_translate("Form", "Start Controllers"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
