 human: 
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint_1_1_position_controller:
    type: effort_controllers/PositionJointInterface
    joint: joint_1


  gazebo_ros_control/pid_gains:
    joint_1: {p: 1.0, i: 0.0, d: 1.0}


    