 human: 
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint_1_x_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_1_x
    pid: {p: 10.0, i: 3.0, d: 1.0}

  joint_1_y_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_1_y
    pid: {p: 0.7, i: 5.0, d: 0}

  joint_1_z_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_1_z
    pid: {p: 0.7, i: 5.0, d: 0}

  # joint_1_x_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: joint_1_x
  #   pid: {p: 100.0, i: 0.01, d: 10.0}

  # joint_1_y_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: joint_1_y
  #   pid: {p: 100.0, i: 0.01, d: 10.0}

  # joint_1_z_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: joint_1_z
  #   pid: {p: 100.0, i: 0.01, d: 10.0}

  gazebo_ros_control/pid_gains:
    joint_1_x: {p: 10.0, i: 3.0, d: 1.0}
    joint_1_y: {p: 0.7, i: 5.0, d: 0}
    joint_1_z: {p: 0.7, i: 5.0, d: 0}


    