 human: 
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint_1_1_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_1_1

  joint_1_2_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_1_2

  joint_1_3_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_1_3


  gazebo_ros_control/pid_gains:
    joint_1_1: {p: 1.0, i: 0.0, d: 1.0}
    joint_1_2: {p: 1.0, i: 0.0, d: 1.0}
    joint_1_3: {p: 1.0, i: 0.0, d: 1.0}


    