 human: 
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint_1_x_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_1_x

  joint_1_y_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_1_y

  joint_1_z_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_1_z


  gazebo_ros_control/pid_gains:
    joint_1_x: {p: 1.0, i: 0.0, d: 1.0}
    joint_1_y: {p: 1.0, i: 0.0, d: 1.0}
    joint_1_z: {p: 1.0, i: 0.0, d: 1.0}


    