 human: 
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  

  # Position Controllers ---------------------------------------
  base_to_upper_trunk_y_position_controller:
    type: position_controllers/JointPositionController
    joint: base_to_upper_trunk_y
    pid: {p: 10.0, i: 30.0, d: 0.1}

  base_to_upper_trunk_x_position_controller:
    type: position_controllers/JointPositionController
    joint: base_to_upper_trunk_x
    pid: {p: 10.0, i: 30.0, d: 0.1}

  base_to_upper_trunk_z_position_controller:
    type: position_controllers/JointPositionController
    joint: base_to_upper_trunk_z
    pid: {p: 10.0, i: 30.0, d: 0.1}

  left_shoulder_y_position_controller:
    type: position_controllers/JointPositionController
    joint: left_shoulder_y
    pid: {p: 10.0, i: 30.0, d: 0.1}

  left_shoulder_x_position_controller:
    type: position_controllers/JointPositionController
    joint: left_shoulder_x
    pid: {p: 10.0, i: 30.0, d: 0.1}

  left_shoulder_z_position_controller:
    type: position_controllers/JointPositionController
    joint: left_shoulder_z
    pid: {p: 10.0, i: 30.0, d: 0.1}

  right_shoulder_y_position_controller:
    type: position_controllers/JointPositionController
    joint: right_shoulder_y
    pid: {p: 10.0, i: 30.0, d: 0.1}

  right_shoulder_x_position_controller:
    type: position_controllers/JointPositionController
    joint: right_shoulder_x
    pid: {p: 10.0, i: 30.0, d: 0.1}

  right_shoulder_z_position_controller:
    type: position_controllers/JointPositionController
    joint: right_shoulder_z
    pid: {p: 10.0, i: 30.0, d: 0.1}

  left_elbow_y_position_controller:
    type: position_controllers/JointPositionController
    joint: left_elbow_y
    pid: {p: 10.0, i: 30.0, d: 0.1}

  left_elbow_z_position_controller:
    type: position_controllers/JointPositionController
    joint: left_elbow_z
    pid: {p: 10.0, i: 30.0, d: 0.1}

  right_elbow_y_position_controller:
    type: position_controllers/JointPositionController
    joint: right_elbow_y
    pid: {p: 10.0, i: 30.0, d: 0.1}

  right_elbow_z_position_controller:
    type: position_controllers/JointPositionController
    joint: right_elbow_z
    pid: {p: 10.0, i: 30.0, d: 0.1}


  gazebo_ros_control/pid_gains:
    base_to_upper_trunk_y: {p: 10.0, i: 30.0, d: 0.1}
    base_to_upper_trunk_x: {p: 10.0, i: 30.0, d: 0.1}
    base_to_upper_trunk_z: {p: 10.0, i: 30.0, d: 0.1}
    left_shoulder_y: {p: 10.0, i: 30.0, d: 0.1}
    left_shoulder_x: {p: 10.0, i: 30.0, d: 0.1}
    left_shoulder_z: {p: 10.0, i: 30.0, d: 0.1}
    right_shoulder_y: {p: 10.0, i: 30.0, d: 0.1}
    right_shoulder_x: {p: 10.0, i: 30.0, d: 0.1}
    right_shoulder_z: {p: 10.0, i: 30.0, d: 0.1}
    left_elbow_y: {p: 10.0, i: 30.0, d: 0.1}
    left_elbow_z: {p: 10.0, i: 30.0, d: 0.1}
    right_elbow_y: {p: 10.0, i: 30.0, d: 0.1}
    right_elbow_z: {p: 10.0, i: 30.0, d: 0.1}


    